### ISSUE TITLE
Not pushing to Dockerhub

### ISSUE THREAD

**Issue by iHiD** [exercism/rust-representer#7]
This doesn't seem to be pushing to Dockerhub (there's no `production` tagged version on https://hub.docker.com/r/exercism/rust-representer/tags?page=1&ordering=last_updated)

That's then breaking the script that we use to update everything. @ErikSchierboom Could you solve this pls :)

**Comment by ErikSchierboom** [comment]
@iHiD The problem was that the Docker image could not be built. There was an [open PR](#2) that fixed this, which I've updated and merged. The Docker image is now pushed succesfully to Docker Hub and ECR: https://github.com/exercism/rust-representer/runs/1985795160?check_suite_focus=true
